//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine
{
    using System;
    using System.Collections.Generic;
    
    public partial class n2mOrderDriver
    {
        public long Id { get; set; }
        public Nullable<long> Order { get; set; }
        public Nullable<long> Driver { get; set; }
    
        public virtual tblDriver tblDriver { get; set; }
        public virtual tblOrder tblOrder { get; set; }
    }
}
