//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppExample.DataAccessLayer.Engine
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrder()
        {
            this.n2mOrderDriver = new HashSet<n2mOrderDriver>();
        }
    
        public long Id { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTimeOffset> StartDateTime { get; set; }
        public Nullable<System.DateTimeOffset> ControlDateTime { get; set; }
        public Nullable<System.DateTimeOffset> CloseDateTime { get; set; }
        public Nullable<long> Customer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<n2mOrderDriver> n2mOrderDriver { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
