CREATE TABLE tblDirectoryValue (
    Id BIGINT IDENTITY (1,1) NOT NULL PRIMARY KEY, 
    EnumName NVARCHAR(16), 
    DirectoryId BIGINT NOT NULL FOREIGN KEY REFERENCES tblDirectory(Id),
    IsReadOnly BIT NOT NULL  DEFAULT(0), 
	IsDeleted BIT NOT NULL DEFAULT(0)
);
GO
