//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DataAccessLayer.Logging
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Cmn_DAL_Logging_Entities : DbContext
    {
        public Cmn_DAL_Logging_Entities()
            : base("name=Cmn_DAL_Logging_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblConfiguration> tblConfiguration { get; set; }
        public virtual DbSet<tblExceptionInfo> tblExceptionInfo { get; set; }
        public virtual DbSet<tblLogItem> tblLogItem { get; set; }
        public virtual DbSet<tblSystemInfo> tblSystemInfo { get; set; }
    }
}
