//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DataAccessLayer.Logging
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExceptionInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblExceptionInfo()
        {
            this.tblExceptionInfo1 = new HashSet<tblExceptionInfo>();
            this.tblLogItem = new HashSet<tblLogItem>();
        }
    
        public long Id { get; set; }
        public Nullable<long> InnerExceptionId { get; set; }
        public System.DateTimeOffset DateTime { get; set; }
        public string Levels { get; set; }
        public string Value { get; set; }
        public string Data { get; set; }
        public string TargetSite { get; set; }
        public string Message { get; set; }
        public string StackTrace { get; set; }
        public string Sources { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblExceptionInfo> tblExceptionInfo1 { get; set; }
        public virtual tblExceptionInfo tblExceptionInfo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLogItem> tblLogItem { get; set; }
    }
}
