//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DataAccessLayer.Logging
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogItem
    {
        public long Id { get; set; }
        public System.DateTimeOffset DateTime { get; set; }
        public string Value { get; set; }
        public string Comment { get; set; }
        public long ApplicationId { get; set; }
        public long LayerId { get; set; }
        public long SubsystemId { get; set; }
        public long MethodId { get; set; }
        public string MethodName { get; set; }
        public Nullable<long> StringNumber { get; set; }
        public Nullable<long> SystemInfoId { get; set; }
        public Nullable<long> ExceptionInfoId { get; set; }
    
        public virtual tblExceptionInfo tblExceptionInfo { get; set; }
        public virtual tblSystemInfo tblSystemInfo { get; set; }
    }
}
