//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DataAccessLayer.Logging
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSystemInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSystemInfo()
        {
            this.tblLogItem = new HashSet<tblLogItem>();
        }
    
        public long Id { get; set; }
        public string CommandLine { get; set; }
        public string CurrentDirectory { get; set; }
        public string MachineName { get; set; }
        public string OSVersion { get; set; }
        public bool Is64BitOperatingSystem { get; set; }
        public string ProcessorCount { get; set; }
        public string StackTrace { get; set; }
        public string SystemDirectory { get; set; }
        public string SystemPageSize { get; set; }
        public string UserName { get; set; }
        public string UserDomainName { get; set; }
        public string GetLogicalDrives { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLogItem> tblLogItem { get; set; }
    }
}
