//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DataAccessLayer.DirLangStrings
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDirectory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDirectory()
        {
            this.tblDirectoryValue = new HashSet<tblDirectoryValue>();
        }
    
        public long Id { get; set; }
        public string EnumName { get; set; }
        public Nullable<bool> IsReadOnly { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDirectoryValue> tblDirectoryValue { get; set; }
    }
}
