//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DataAccessLayer.DirLangStrings
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDirectoryValue
    {
        public long Id { get; set; }
        public string EnumName { get; set; }
        public Nullable<bool> IsReadOnly { get; set; }
        public Nullable<long> DirectoryId { get; set; }
    
        public virtual tblDirectory tblDirectory { get; set; }
    }
}
