//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DataAccessLayer.AppIdAndAuth
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Common_AppIdAndAuth_Entities : DbContext
    {
        public Common_AppIdAndAuth_Entities()
            : base("name=Common_AppIdAndAuth_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAuthenticationActor> tblAuthenticationActor { get; set; }
        public virtual DbSet<tblAuthenticationRole> tblAuthenticationRole { get; set; }
    }
}
