//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DataAccessLayer.AppIdAndAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicationIdLayer
    {
        public long Id { get; set; }
        public string EnumName { get; set; }
    }
}
