//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DataAccessLayer.AppIdAndAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicationIdSubsystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblApplicationIdSubsystem()
        {
            this.tblApplicationIdMethod = new HashSet<tblApplicationIdMethod>();
            this.tblAuthorizationSimpleEntities = new HashSet<tblAuthorizationSimpleEntities>();
        }
    
        public long Id { get; set; }
        public string EnumName { get; set; }
        public long ApplicationId { get; set; }
    
        public virtual tblApplicationIdApplication tblApplicationIdApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblApplicationIdMethod> tblApplicationIdMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAuthorizationSimpleEntities> tblAuthorizationSimpleEntities { get; set; }
    }
}
