//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DataAccessLayer.AppIdAndAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuthorizationSimpleEntities
    {
        public long RoleId { get; set; }
        public long EntityId { get; set; }
        public bool AllowMethodReadWithFilters { get; set; }
        public bool AllowMethodCreateOne { get; set; }
        public bool AllowMethodReadOne { get; set; }
        public bool AllowMethodUpdateOne { get; set; }
        public bool AllowMethodDeleteOne { get; set; }
        public bool AllowMethodCreateMultiple { get; set; }
        public bool AllowMethodReadMultiple { get; set; }
        public bool AllowMethodUpdateMultiple { get; set; }
        public bool AllowMethodDeleteMultiple { get; set; }
        public bool AllowMethodCreateLink { get; set; }
        public bool AllowMethodReadLink { get; set; }
        public bool AllowMethodUpdateLink { get; set; }
        public bool AllowMethodDeleteLink { get; set; }
    
        public virtual tblApplicationIdSubsystem tblApplicationIdSubsystem { get; set; }
        public virtual tblAuthenticationRole tblAuthenticationRole { get; set; }
    }
}
