//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppExample.DataAccessLayer.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        public long Id { get; set; }
        public string Comment { get; set; }
        public Nullable<long> Balance { get; set; }
        public Nullable<long> AccountState { get; set; }
    
        public virtual tblDirectoryValue tblDirectoryValue { get; set; }
    }
}
