//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppExample.DataAccessLayer.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public long Id { get; set; }
        public string Comment { get; set; }
        public Nullable<long> Position { get; set; }
        public Nullable<long> PersonId { get; set; }
        public string PersonComment { get; set; }
        public string PersonFirstName { get; set; }
        public string PersonSurname { get; set; }
        public string PersonPatronymicName { get; set; }
        public Nullable<long> PersonGender { get; set; }
        public Nullable<long> PersonMaritalStatus { get; set; }
        public Nullable<System.DateTimeOffset> PersonBirthDate { get; set; }
        public Nullable<long> PersonAmountOfChildren { get; set; }
        public string PersonAddressOfCurrLivingPlace { get; set; }
        public Nullable<long> PersonContactsId { get; set; }
        public string PersonContactsActualAddress { get; set; }
        public string PersonContactsFormalAddress { get; set; }
        public string PersonContactsPersonalMobilePhone { get; set; }
        public string PersonContactsWorkMobilePhone { get; set; }
        public string PersonContactsHomePhone { get; set; }
        public string PersonContactsWorkPhone { get; set; }
        public string PersonContactsPersonalEMail { get; set; }
        public string PersonContactsWorkEMail { get; set; }
        public string PersonContactsMessenger1 { get; set; }
        public string PersonContactsMessenger2 { get; set; }
        public string PersonContactsMessenger3 { get; set; }
        public Nullable<long> PersonPassportInfoId { get; set; }
        public string PersonPassportInfoComment { get; set; }
        public string PersonPassportInfoSeries { get; set; }
        public string PersonPassportInfoNumber { get; set; }
        public Nullable<System.DateTimeOffset> PersonPassportInfoIssueDate { get; set; }
        public string PersonPassportInfoWhoIsIssuer { get; set; }
        public string PersonPassportInfoAddressOfResidence { get; set; }
        public string PersonPassportInfoAddressOfRegistration { get; set; }
        public Nullable<System.DateTimeOffset> PersonPassportInfoLastChangeDate { get; set; }
    
        public virtual tblDirectoryValue tblDirectoryValue { get; set; }
        public virtual tblDirectoryValue tblDirectoryValue1 { get; set; }
        public virtual tblDirectoryValue tblDirectoryValue2 { get; set; }
    }
}
