//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppExample.DataAccessLayer.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVehicle()
        {
            this.tblDriver = new HashSet<tblDriver>();
        }
    
        public long Id { get; set; }
        public string Comment { get; set; }
        public Nullable<long> Brand { get; set; }
        public string Model { get; set; }
        public Nullable<long> DriverOwner { get; set; }
    
        public virtual tblDirectoryValue tblDirectoryValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDriver> tblDriver { get; set; }
        public virtual tblDriver tblDriver1 { get; set; }
    }
}
